import { StoreBenefit } from '../types/card';

export const BENEFIT_DATA: StoreBenefit[] = [
  // 올리브영
  { id: 'b-shinhan-deep-dream-oliveyoung', cardId: 'shinhan-deep-dream', storeNames: ['올리브영', 'OLIVEYOUNG', 'Olive Young'], category: 'beauty', benefitType: 'cashback', discountRate: null, cashbackRate: 0.10, pointRate: null, benefitDescription: '전월실적 30만원 이상 시 10% 캐시백 (월 1만원 한도)', minimumSpend: 300000, monthlyCap: 10000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-kb-titanium-oliveyoung', cardId: 'kb-titanium', storeNames: ['올리브영', 'OLIVEYOUNG', 'Olive Young'], category: 'beauty', benefitType: 'discount', discountRate: 0.07, cashbackRate: null, pointRate: null, benefitDescription: '7% 할인 (전월실적 50만원 이상)', minimumSpend: 500000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-hyundai-zero-oliveyoung', cardId: 'hyundai-zero-edition2', storeNames: ['올리브영', 'OLIVEYOUNG', 'Olive Young'], category: 'beauty', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (월 5천원 한도)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-samsung-taptap-oliveyoung', cardId: 'samsung-taptap-o', storeNames: ['올리브영', 'OLIVEYOUNG', 'Olive Young'], category: 'beauty', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (온·오프라인)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: true, lastVerified: '2025-01-01' },

  // 스타벅스
  { id: 'b-shinhan-deep-dream-starbucks', cardId: 'shinhan-deep-dream', storeNames: ['스타벅스', 'Starbucks', 'STARBUCKS'], category: 'coffee', benefitType: 'discount', discountRate: 0.10, cashbackRate: null, pointRate: null, benefitDescription: '10% 할인 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-kb-titanium-starbucks', cardId: 'kb-titanium', storeNames: ['스타벅스', 'Starbucks', 'STARBUCKS'], category: 'coffee', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (월 3천원 한도)', minimumSpend: 200000, monthlyCap: 3000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-samsung-id-on-starbucks', cardId: 'samsung-id-on', storeNames: ['스타벅스', 'Starbucks', 'STARBUCKS'], category: 'coffee', benefitType: 'cashback', discountRate: null, cashbackRate: 0.10, pointRate: null, benefitDescription: '10% 캐시백 (월 2회)', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-hyundai-m3-starbucks', cardId: 'hyundai-m3', storeNames: ['스타벅스', 'Starbucks', 'STARBUCKS'], category: 'coffee', benefitType: 'point', discountRate: null, cashbackRate: null, pointRate: 0.15, benefitDescription: 'M포인트 15% 적립', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },

  // 메가커피
  { id: 'b-shinhan-deep-dream-mega', cardId: 'shinhan-deep-dream', storeNames: ['메가커피', '메가MGC커피', 'MEGA COFFEE', 'Mega Coffee'], category: 'coffee', benefitType: 'discount', discountRate: 0.10, cashbackRate: null, pointRate: null, benefitDescription: '10% 할인 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-kb-woori-mega', cardId: 'kb-woori-together', storeNames: ['메가커피', '메가MGC커피', 'MEGA COFFEE', 'Mega Coffee'], category: 'coffee', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (월 2천원 한도)', minimumSpend: null, monthlyCap: 2000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-hyundai-zero-mega', cardId: 'hyundai-zero-edition2', storeNames: ['메가커피', '메가MGC커피', 'MEGA COFFEE', 'Mega Coffee'], category: 'coffee', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },

  // 이디야
  { id: 'b-shinhan-deep-dream-ediya', cardId: 'shinhan-deep-dream', storeNames: ['이디야', '이디야커피', 'EDIYA', 'EDIYA COFFEE'], category: 'coffee', benefitType: 'discount', discountRate: 0.10, cashbackRate: null, pointRate: null, benefitDescription: '10% 할인 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-samsung-taptap-ediya', cardId: 'samsung-taptap-o', storeNames: ['이디야', '이디야커피', 'EDIYA', 'EDIYA COFFEE'], category: 'coffee', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },

  // GS25
  { id: 'b-shinhan-deep-dream-gs25', cardId: 'shinhan-deep-dream', storeNames: ['GS25', 'GS 25', 'GS편의점'], category: 'convenience', benefitType: 'discount', discountRate: 0.05, cashbackRate: null, pointRate: null, benefitDescription: '5% 할인 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-kb-titanium-gs25', cardId: 'kb-titanium', storeNames: ['GS25', 'GS 25', 'GS편의점'], category: 'convenience', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (월 5천원 한도)', minimumSpend: 200000, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-lotte-likit-gs25', cardId: 'lotte-likit', storeNames: ['GS25', 'GS 25', 'GS편의점'], category: 'convenience', benefitType: 'point', discountRate: null, cashbackRate: null, pointRate: 0.10, benefitDescription: '10% 포인트 적립', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-woori-gs25', cardId: 'woori-da-living', storeNames: ['GS25', 'GS 25', 'GS편의점'], category: 'convenience', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (무실적, 월 3천원 한도)', minimumSpend: null, monthlyCap: 3000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },

  // CU
  { id: 'b-shinhan-deep-dream-cu', cardId: 'shinhan-deep-dream', storeNames: ['CU', 'CU편의점', '씨유'], category: 'convenience', benefitType: 'discount', discountRate: 0.05, cashbackRate: null, pointRate: null, benefitDescription: '5% 할인 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-kb-titanium-cu', cardId: 'kb-titanium', storeNames: ['CU', 'CU편의점', '씨유'], category: 'convenience', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (월 5천원 한도)', minimumSpend: 200000, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-nh-cu', cardId: 'nh-all-at-once', storeNames: ['CU', 'CU편의점', '씨유'], category: 'convenience', benefitType: 'cashback', discountRate: null, cashbackRate: 0.07, pointRate: null, benefitDescription: '7% 캐시백 (CU 제휴, 월 5천원 한도)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },

  // 쿠팡
  { id: 'b-shinhan-deep-dream-coupang', cardId: 'shinhan-deep-dream', storeNames: ['쿠팡', 'COUPANG', '쿠팡로켓', '쿠팡이츠'], category: 'online_shopping', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },
  { id: 'b-kb-titanium-coupang', cardId: 'kb-titanium', storeNames: ['쿠팡', 'COUPANG', '쿠팡로켓', '쿠팡이츠'], category: 'online_shopping', benefitType: 'cashback', discountRate: null, cashbackRate: 0.07, pointRate: null, benefitDescription: '7% 캐시백 (전월실적 50만원 이상, 월 1만원 한도)', minimumSpend: 500000, monthlyCap: 10000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },
  { id: 'b-samsung-id-on-coupang', cardId: 'samsung-id-on', storeNames: ['쿠팡', 'COUPANG', '쿠팡로켓', '쿠팡이츠'], category: 'online_shopping', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (월 5천원 한도)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },
  { id: 'b-hyundai-zero-coupang', cardId: 'hyundai-zero-edition2', storeNames: ['쿠팡', 'COUPANG', '쿠팡로켓', '쿠팡이츠'], category: 'online_shopping', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (월 5천원 한도)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },

  // 배달의민족
  { id: 'b-shinhan-deep-dream-baemin', cardId: 'shinhan-deep-dream', storeNames: ['배달의민족', '배민', 'BAEMIN', '배민1'], category: 'food', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },
  { id: 'b-samsung-taptap-baemin', cardId: 'samsung-taptap-o', storeNames: ['배달의민족', '배민', 'BAEMIN', '배민1'], category: 'food', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '5% 캐시백 (월 5천원 한도)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },
  { id: 'b-kb-woori-baemin', cardId: 'kb-woori-together', storeNames: ['배달의민족', '배민', 'BAEMIN', '배민1'], category: 'food', benefitType: 'cashback', discountRate: null, cashbackRate: 0.03, pointRate: null, benefitDescription: '3% 캐시백 (무실적, 월 3천원 한도)', minimumSpend: null, monthlyCap: 3000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },

  // CGV / 영화관
  { id: 'b-shinhan-deep-dream-cgv', cardId: 'shinhan-deep-dream', storeNames: ['CGV', 'CGV영화관', 'CJ CGV'], category: 'cinema', benefitType: 'discount', discountRate: null, cashbackRate: null, pointRate: null, benefitDescription: '최대 6,000원 할인 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-kb-titanium-cgv', cardId: 'kb-titanium', storeNames: ['CGV', 'CGV영화관', 'CJ CGV', '롯데시네마', 'LOTTE CINEMA', '메가박스', 'MEGABOX'], category: 'cinema', benefitType: 'discount', discountRate: null, cashbackRate: null, pointRate: null, benefitDescription: '4,000원 할인 (전월실적 20만원 이상)', minimumSpend: 200000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-hyundai-m3-cinema', cardId: 'hyundai-m3', storeNames: ['CGV', 'CGV영화관', '롯데시네마', 'LOTTE CINEMA', '메가박스', 'MEGABOX'], category: 'cinema', benefitType: 'discount', discountRate: null, cashbackRate: null, pointRate: null, benefitDescription: '6,000원 할인 (월 2회)', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-samsung-id-on-cinema', cardId: 'samsung-id-on', storeNames: ['CGV', 'CGV영화관', '롯데시네마', '메가박스'], category: 'cinema', benefitType: 'discount', discountRate: null, cashbackRate: null, pointRate: null, benefitDescription: '전 영화관 5,000원 할인', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },

  // 대중교통
  { id: 'b-shinhan-mycar-transport', cardId: 'shinhan-mycar', storeNames: ['대중교통', '지하철', '버스', '교통카드'], category: 'transport', benefitType: 'cashback', discountRate: null, cashbackRate: 0.10, pointRate: null, benefitDescription: '대중교통 10% 캐시백 (월 5천원 한도)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-kb-woori-transport', cardId: 'kb-woori-together', storeNames: ['대중교통', '지하철', '버스', '교통카드'], category: 'transport', benefitType: 'cashback', discountRate: null, cashbackRate: 0.10, pointRate: null, benefitDescription: '대중교통 10% 캐시백 (월 5천원 한도)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-hyundai-zero-transport', cardId: 'hyundai-zero-edition2', storeNames: ['대중교통', '지하철', '버스', '교통카드'], category: 'transport', benefitType: 'cashback', discountRate: null, cashbackRate: 0.10, pointRate: null, benefitDescription: '대중교통 10% 캐시백 (ZERO 교통형)', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-nh-transport', cardId: 'nh-all-at-once', storeNames: ['대중교통', '지하철', '버스', '교통카드'], category: 'transport', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '대중교통 5% 캐시백 (월 3천원 한도)', minimumSpend: null, monthlyCap: 3000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },

  // 주유
  { id: 'b-shinhan-mycar-gas', cardId: 'shinhan-mycar', storeNames: ['주유소', 'SK에너지', 'GS칼텍스', 'S-OIL', '현대오일뱅크', '알뜰주유소'], category: 'gas', benefitType: 'discount', discountRate: null, cashbackRate: null, pointRate: null, benefitDescription: 'L당 60원 할인 (전국 SK·GS·S-OIL·현대)', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-kb-titanium-gas', cardId: 'kb-titanium', storeNames: ['주유소', 'SK에너지', 'GS칼텍스', 'S-OIL', '현대오일뱅크'], category: 'gas', benefitType: 'cashback', discountRate: null, cashbackRate: 0.04, pointRate: null, benefitDescription: '주유 4% 캐시백 (전월실적 20만원 이상, 월 5천원 한도)', minimumSpend: 200000, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-hyundai-m3-gas', cardId: 'hyundai-m3', storeNames: ['주유소', 'SK에너지', 'GS칼텍스', 'S-OIL', '현대오일뱅크'], category: 'gas', benefitType: 'point', discountRate: null, cashbackRate: null, pointRate: 0.05, benefitDescription: '주유 M포인트 5% 적립', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: false, isOffline: true, lastVerified: '2025-01-01' },

  // 이마트 / 마트
  { id: 'b-samsung-id-on-emart', cardId: 'samsung-id-on', storeNames: ['이마트', 'E마트', 'SSG', 'SSG.COM', '신세계'], category: 'online_shopping', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '이마트/SSG 5% 캐시백 (월 5천원 한도)', minimumSpend: null, monthlyCap: 5000, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: true, lastVerified: '2025-01-01' },
  { id: 'b-lotte-likit-lottemart', cardId: 'lotte-likit', storeNames: ['롯데마트', '롯데온', 'LOTTE MART', '롯데슈퍼'], category: 'online_shopping', benefitType: 'point', discountRate: null, cashbackRate: null, pointRate: 0.10, benefitDescription: '롯데마트/롯데온 10% 포인트 적립', minimumSpend: null, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: true, lastVerified: '2025-01-01' },

  // 통신요금
  { id: 'b-kb-titanium-telecom', cardId: 'kb-titanium', storeNames: ['SKT', 'KT', 'LGU+', 'LG U+', '통신요금', 'T월드', '올레', 'U+'], category: 'etc', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '통신요금 5% 캐시백 (자동납부, 전월실적 20만원 이상)', minimumSpend: 200000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },
  { id: 'b-shinhan-deep-dream-telecom', cardId: 'shinhan-deep-dream', storeNames: ['SKT', 'KT', 'LGU+', 'LG U+', '통신요금', 'T월드', '올레', 'U+'], category: 'etc', benefitType: 'cashback', discountRate: null, cashbackRate: 0.05, pointRate: null, benefitDescription: '통신요금 5% 캐시백 (전월실적 30만원 이상)', minimumSpend: 300000, monthlyCap: null, weekdayOnly: false, weekendOnly: false, isOnline: true, isOffline: false, lastVerified: '2025-01-01' },
];
