import { Card } from '../types/card';

export const CARD_MASTER_DATA: Card[] = [
  {
    id: 'shinhan-deep-dream',
    issuer: 'shinhan',
    name: '신한카드 Deep Dream',
    annualFee: 15000,
    primaryColor: '#005BAC',
    ocrKeywords: ['신한', 'SHINHAN', 'DEEP DREAM', 'Deep Dream'],
  },
  {
    id: 'shinhan-mycar',
    issuer: 'shinhan',
    name: '신한카드 마이카',
    annualFee: 10000,
    primaryColor: '#0076CE',
    ocrKeywords: ['신한', 'SHINHAN', '마이카'],
  },
  {
    id: 'kb-titanium',
    issuer: 'kb',
    name: 'KB국민 티타늄카드',
    annualFee: 15000,
    primaryColor: '#888B8D',
    ocrKeywords: ['KB국민', 'KB', 'TITANIUM', '티타늄'],
  },
  {
    id: 'kb-woori-together',
    issuer: 'kb',
    name: 'KB국민 우리동네 카드',
    annualFee: 0,
    primaryColor: '#FFBC00',
    ocrKeywords: ['KB국민', 'KB', '우리동네'],
  },
  {
    id: 'hyundai-zero-edition2',
    issuer: 'hyundai',
    name: '현대카드 ZERO Edition2',
    annualFee: 0,
    primaryColor: '#002C5F',
    ocrKeywords: ['현대카드', 'HYUNDAICARD', 'ZERO', 'Edition2'],
  },
  {
    id: 'hyundai-m3',
    issuer: 'hyundai',
    name: '현대카드 M3',
    annualFee: 30000,
    primaryColor: '#1A1A1A',
    ocrKeywords: ['현대카드', 'HYUNDAICARD', 'M3'],
  },
  {
    id: 'samsung-id-on',
    issuer: 'samsung',
    name: '삼성카드 iD ON',
    annualFee: 20000,
    primaryColor: '#1428A0',
    ocrKeywords: ['삼성카드', 'SAMSUNG', 'iD ON'],
  },
  {
    id: 'samsung-taptap-o',
    issuer: 'samsung',
    name: '삼성카드 taptap O',
    annualFee: 0,
    primaryColor: '#FF6900',
    ocrKeywords: ['삼성카드', 'SAMSUNG', 'taptap'],
  },
  {
    id: 'lotte-likit',
    issuer: 'lotte',
    name: '롯데카드 likit',
    annualFee: 10000,
    primaryColor: '#ED1C24',
    ocrKeywords: ['롯데카드', 'LOTTE', 'likit'],
  },
  {
    id: 'hana-1q-card',
    issuer: 'hana',
    name: '하나카드 1Q카드',
    annualFee: 0,
    primaryColor: '#009B77',
    ocrKeywords: ['하나카드', 'HANA', '1Q'],
  },
  {
    id: 'woori-da-living',
    issuer: 'woori',
    name: '우리카드 다살림',
    annualFee: 0,
    primaryColor: '#0066B3',
    ocrKeywords: ['우리카드', 'WOORI', '다살림'],
  },
  {
    id: 'nh-all-at-once',
    issuer: 'nh',
    name: 'NH농협카드 올원',
    annualFee: 10000,
    primaryColor: '#00A650',
    ocrKeywords: ['NH농협', 'NH', '올원'],
  },
];

export const ISSUER_LABEL: Record<string, string> = {
  shinhan: '신한카드',
  kb: 'KB국민카드',
  hyundai: '현대카드',
  samsung: '삼성카드',
  lotte: '롯데카드',
  hana: '하나카드',
  woori: '우리카드',
  bc: 'BC카드',
  nh: 'NH농협카드',
};
